# Covariáveis

	Variações ambientais ou amostrais (p.ex. região geográfica, tipo de vegetação, horário do dia, condições climáticas, número de observadores, tamanho dos grupos...) podem influenciar tanto nas abundâncias/densidades das populações quanto na sua detectabilidade. Por exemplo, a abundância das espécies pode variar entre regiões geográficas, ou o horário de atividade da espécie pode influenciar na sua detectabilidade, ou o número de observadores pode aumentar a detectabilidade. Essas são hipóteses que podem ser verificadas com uma exploração prévia dos dados (p. ex. frequência de observações x distância / região geográfica), antes de serem consideradas fontes de variação. 
Quando a heterogeneidade é grande o suficiente para enviesar as observações, a variabilidade dos dados pode prejudicar o ajuste de uma função de detecção global. Dois caminhos são possíveis para lidar com esse tipo de variação. O primeiro deles, e mais recomendável, é tratar as variáveis como covariáveis, pela abordagem da Amostragem por Distância com Múltiplas Covariáveis (Multiple Covariate Distance Sampling, MCDS, (MARQUES; BUCKLAND, 2003; MARQUES et al., 2007).  O segundo caminho é estratificar os dados, dividindo as observações em subconjuntos (Seção 10). As vantagens do uso de covariáveis em relação a estratificação são a de requerer uma quantidade menor de dados e influenciar somente o parâmetro escalar da função de detecção, sem alterar a forma. As covariáveis (z) são incorporadas aos modelos através dos parâmetros escalares das funções-chave, chamados de sigma (σ). As funções chaves que apresentam parâmetro escalar são half-normal e hazard-rate:


Sendo k usado para se referir à função-chave. As covariáveis são incluídas ao se considerar o parâmetro escalar destas funções como uma exponencial de um modelo linear de (J) covariáveis (z, um vetor de J covariáveis para cada observação).


A distribuição das covariáveis não é conhecida, o que terá efeito sobre o cálculo da detectabilidade. A estratégia seguida por MIILER et al (2019) é a mesma sugerida por MARQUES e BUCKLAND (2003), de calcular a probabilidade de detecção de forma condicional às covariáveis. No pacote Distance para o R, o uso de covariáveis é definido através do argumento ‘formula’ da função ‘ds’, adaptada no pacote distanceMonitoraflorestal para a função ‘ajustar_modelos_Distance’ no pacote distanceMonitoraflorestal.

	Uma boa escolha de covariáveis passa por um bom processo exploratório dos dados. É importante avaliar como fatores ambientais ou amostrais podem influenciar de forma significativa a detectabilidade dos animais. Para os dados do Programa Monitora, uma das principais covariáveis a ser considerada é o tamanho do grupo (s, que deve ser chamada de size para o pacote Distance). Um dos efeitos esperados para espécies que formam grupos é o chamado viés de tamanho. A tendência é que a pequenas distâncias todos os grupos sejam detectáveis, mas somente os grupos maiores serão detectados a distâncias maiores. A abordagem padrão implementada no programa DISTANCE é a de lidar com o efeito do tamanho do grupo usando métodos de regressão. É possível também estratificar os dados por categorias de tamanho ou truncar a partir do ponto onde surge o viés. Entretanto, a estratégia mais recomendada atualmente é usar o tamanho do grupo como uma covariável pela abordagem MCDS. Esta é uma covariável especial, pois será usada tanto para corrigir efeitos de viés na detectabilidade como para corrigir a abundância. Para espécies que não formam grupos, cada observação é considerada um indivíduo (si = 1). Para as que formam grupos, as informações de tamanho entrarão no cálculo da abundância. Nesses casos, o estimador de abundância Horvitz-Thompson, usado para estimar as abundâncias no Distance, irá incorporar tanto as informações do tamanho do grupo (si) quanto da probabilidade de detecção condicionada às covariáveis (p(zi)) pelo MCDS:

Utilizamos o tamanho do grupo como covariável no fluxo 4. Além do tamanho do grupo, outras covariáveis podem ser consideradas a partir dos dados do Programa Monitora, como: ano de amostragem, número de observadores, horário do dia, tempo após o início da amostragem. Além do tamanho do grupo, testamos o horário após o início da amostragem no fluxo 4. No fluxo 5, utilizamos o ano de amostragem como covariável.  
