# Estratificação

Atualmente, O MCDS é o método mais utilizado. A estratificação ainda é uma estratégia bastante utilizada para estratos geográficos (Region.Label) (BUCKLAND et al., 2015; MILLER et al., 2019), apesar de ser possível tratar os mesmos como covariáveis. No caso dos dados do Programa Monitora, a estratificação geográfica pode ser utilizada para dados de uma mesma espécie para diferentes UCs. Nesse caso, cada uma das UCs pode ser tratada como um estrato geográfico (Region.Label). Apresentamos um exemplo de estratificação no fluxo 6. 

Quando os dados são estratificados, ajusta-se uma função de detecção para os dados globais e para cada um subconjunto de dados, para estimar as abundâncias/densidades. Quando a estratificação é feita após a coleta e análise dos dados, é chamada de pós-estratificação. Esta estratégia é aceita, porém requer um cuidado maior para não subestimar/superestimar as abundâncias. O segundo caminho é A estratificação dos dados é considerada muitas vezes desvantajosa em relação ao MCDS, pois reduz os tamanhos amostrais e pode resultar em estimativas enviesadas das funções de detecção. A estratificação só será adequada quando o número de observações for grande para assegurar suficiência amostral dentro de cada estrato (as recomendações em termos de suficiência, nesse caso, se aplicam aos estratos pois as funções de detecção serão ajustadas por estrato). Um critério para avaliar se o ajuste das funções para os dados estratificados foi melhor que para os dados globais é a comparação do somatório dos valores de AIC para cada estrato com o valor de AIC do modelo global. Se a soma dos valores de AIC dos estratos for menor que o AIC global, significa que o ajuste foi melhor para os dados estratificados.